#!/bin/sh

# pandoc-from-markdown-to-pdf
#
# Use the pandoc command to convert from a markdown file to a PDF file.
#
# This tool uses our favorite settings. Customize these as you like.
#
# Syntax:
#
# ```sh
# pandoc-from-markdown-to-pdf <args>
# ```
#
# Syntax for typical use:
#
# ```sh
# pandoc-from-markdown-to-pdf <input.md> -o <output.pdf>
# ```
#
# Example:
#
# ```sh
# $ pandoc-from-markdown-to-pdf example.md -o example.pdf
# ```
#
#
# ## Availability
#
# This tool is currently tested on macOS Monterey.
#
# If you want to use this tool on other systems,
# then please contact us, or open an issue, to let us know.
#
#
# ## Prerequisites
#
# This script requires pandoc and xelatex to be installed.
#
# This script requires these prerequisites to be installed:
#
#   * pandoc document converter
#
#   * xelatex implementation of LaTex converters
#
#   * pygments syntax highlighting
#
#   * Bitstream Vera fonts
# 
# If you want a different choices for any of the above,
# then please contact us or open an issue, to let us know.
#
#
# ### macOS install
#
# Example using brew:
#
# ```sh
# brew install pandoc
# brew install mactex
# ```
#
# Verify the programs are runnable:
#
# ```sh
# $ which pandoc
# /usr/local/bin/pandoc
#
# $ pandoc --version
# pandoc 2.17.1.1
#
# $ which xelatex
# /Library/TeX/texbin/xelatex
#
# $ xelatex --version
# XeTeX 3.141592653-2.6-0.999993 (TeX Live 2021)
# ```
#
#
# ## Help
#
# This script uses Bitstream Vera fonts because they are
# widely available, and use a fair license for this work.
#
#   * main font: Bitstream Vera Serif
#
#   * sans font: Bitstream Vera Sans
#
#   * code font: Bitstream Vera Sans Mono
#
# For help with fonts, see the `fonts` directory:
#
# https://github.com/sixarm/pandoc-from-markdown-to-pdf
#
#
# ## Thanks
#
# Thanks to https://learnbyexample.github.io/customizing-pandoc/
#
# Thanks to https://github.com/sixarm/sixarm-unix-shell-functions/
#

# This section is code from sixarm-unix-shell-functions:
# https://github.com/SixArm/sixarm-unix-shell-functions

EX_UNAVAILABLE=69

die() {
        n="$1" ; shift ; >&2 printf %s\\n "$*" ; exit "$n"
}

cmd() {
        command -v "$1" >/dev/null 2>&1
}

cmd_or_die() {
        cmd "$1" || die "$EX_UNAVAILABLE" "Command needed: $1"
}

font_exists() {
        fc-list | grep -q ": $1:"
}

font_exists_or_die() {
        font_exists "$1" || die "$EX_UNAVAILABLE" "Font needed: $1"
}

# Preflight

cmd_or_die "pandoc"
cmd_or_die "xelatex"

font_exists_or_die "Bitstream Vera Serif"
font_exists_or_die "Bitstream Vera Sans"
font_exists_or_die "Bitstream Vera Sans Mono"

# Main

DIR0=$(dirname "$0")

pandoc \
    -f gfm \
    -V linkcolor:blue \
    -V geometry:a4paper \
    -V geometry:margin=2.5cm \
    -V mainfont="Bitstream Vera Serif" \
    -V sansfont="Bitstream Vera Sans" \
    -V monofont="Bitstream Vera Sans Mono" \
    -V fontsize=12pt \
    --highlight-style="$DIR0/pygments.theme" \
    --pdf-engine=xelatex \
    --include-in-header="$DIR0/tex/chapter.tex" \
    --include-in-header="$DIR0/tex/blockquote.tex" \
    --include-in-header="$DIR0/tex/bullet.tex" \
    --include-in-header="$DIR0/tex/inline_code.tex" \
    --toc \
    --toc-depth=2 \
   "$@" 
