#!/bin/sh

# pandoc-from-markdown-to-pdf
#
# Use the pandoc command to convert from a markdown file to a PDF file.
#
# This tool uses our favorite settings for layouts, styles, fonts, etc.
#
# You can edit this tool as you wish.
#
# Syntax:
#
# ```sh
# pandoc-from-markdown-to-pdf <args>
# ```
#
# Syntax for typical use:
#
# ```sh
# pandoc-from-markdown-to-pdf <input.md> -o <output.pdf>
# ```
#
# Example for typical use:
#
# ```sh
# $ pandoc-from-markdown-to-pdf example.md -o example.pdf
# ```
#
# For documentation, see the `doc` directory.
#
#
# ## Thanks
#
# Thanks to https://learnbyexample.github.io/customizing-pandoc/
#
# Thanks to https://github.com/sixarm/posix-shell-script-kit/
#
#
# ## Tracking
#
# * Command: pandoc-from-markdown-to-pdf
# * Version: 2.0.1
# * Created: 2022-03-13T22:05:34Z
# * Updated: 2023-03-24T13:10:38Z
# * License: GPL-2.0 or GPL-3.0 or contact us for more
# * Website: https://github.com/sixarm/pandoc-from-markdown-to-pdf
# * Contact: Joel Parker Henderson (joel@sixarm.com)

set -euf

# Include https://github.com/SixArm/posix-shell-script-kit
. "$(dirname "$(readlink -f "$0")")/posix-shell-script-kit"

# Preflight

command_exists_or_die "pandoc"
command_exists_or_die "xelatex"

# Choose fonts

# font_name_exists_or_die "Bitstream Vera Serif"
# font_name_exists_or_die "Bitstream Vera Sans"
# font_name_exists_or_die "Bitstream Vera Sans Mono"

# mainfont="Bitstream Vera Serif"
# sansfont="Bitstream Vera Sans"
# monofont="Bitstream Vera Sans Mono"

font_name_exists_or_die "Source Serif Pro"
font_name_exists_or_die "Source Sans Pro"
font_name_exists_or_die "Source Code Pro"

mainfont="Source Serif Pro"
sansfont="Source Sans Pro"
monofont="Source Code Pro"

# Main

DIR0=$(dirname "$0")

pandoc \
    -V linkcolor:blue \
    -V geometry:a4paper \
    -V geometry:margin=2.5cm \
    -V mainfont="$mainfont" \
    -V sansfont="$sansfont" \
    -V monofont="$monofont" \
    -V fontsize=12pt \
    --listings \
    --toc \
    --toc-depth=2 \
    --pdf-engine=xelatex \
    --include-in-header="$DIR0/tex/chapter.tex" \
    --include-in-header="$DIR0/tex/blockquote.tex" \
    --include-in-header="$DIR0/tex/bullet.tex" \
    --include-in-header="$DIR0/tex/fontspec.tex" \
    --include-in-header="$DIR0/tex/hyphen.tex" \
    --include-in-header="$DIR0/tex/inline_code.tex" \
    --include-in-header="$DIR0/tex/listings.tex" \
    --include-in-header="$DIR0/tex/setspace.tex" \
    --include-in-header="$DIR0/tex/raggedright.tex" \
   "$@" 

# Other ideas to consider:
#
#     -f gfm \
#     --highlight-style="$DIR0/pygments.theme" \
#     --template eisvogel_mod
#     --columns=50
#     --number-sections
#     --pdf-engine lualatex
#     --dpi=300 -M 
#     date="$DATE" 
#     HEADER.YAML 
#     $SOURCE.md
